-- FINAL SQL: Artikelsuche ohne Kategorie + täglicher Mailbericht

-- Artikeldaten / Stammdaten
create table if not exists public.artikel_stammdaten (
  id bigint generated by default as identity primary key,
  barcode text unique not null,
  artikelnummer text,
  name text,
  bild_url text,
  updated_at timestamp with time zone default now()
);

alter table if exists public.mhd_artikel add column if not exists barcode text;
alter table if exists public.mhd_artikel add column if not exists artikelnummer text;
alter table if exists public.mhd_artikel add column if not exists bild_url text;

-- Abschriften / Kontrollen
alter table if exists public.abschriften add column if not exists typ text default 'ware';
alter table if exists public.abschriften add column if not exists status text default 'offen';
alter table if exists public.abschriften add column if not exists final_abgesendet boolean default false;
alter table if exists public.abschriften add column if not exists datum date default current_date;
alter table if exists public.abschriften add column if not exists name text;
alter table if exists public.abschriften add column if not exists artikel text;
alter table if exists public.abschriften add column if not exists menge integer default 0;
alter table if exists public.abschriften add column if not exists mitarbeiter text;

alter table public.artikel_stammdaten disable row level security;
alter table public.mhd_artikel disable row level security;
alter table public.abschriften disable row level security;
alter table public.mitarbeiter disable row level security;

-- Für automatische E-Mail:
-- 1) Supabase Edge Function daily-mhd-report deployen
-- 2) Secret RESEND_API_KEY setzen
-- 3) Cron in Supabase Dashboard auf 07:00 Uhr Europe/Berlin setzen:
--    GET https://<PROJECT_REF>.functions.supabase.co/daily-mhd-report
