-- FINAL SQL: Fehlende Artikel

create table if not exists public.fehlende_artikel (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  barcode text not null,
  hinweis text,
  gemeldet_von text,
  gemeldet_von_nummer int,
  status text default 'offen',
  erledigt_am timestamp with time zone,
  erledigt_von text
);

create index if not exists fehlende_artikel_barcode_status_idx
on public.fehlende_artikel (barcode, status);

alter table public.fehlende_artikel disable row level security;
