-- FINAL SUPABASE SQL ERWEITERUNG

alter table if exists public.abschriften add column if not exists typ text default 'ware';
alter table if exists public.abschriften add column if not exists status text default 'offen';
alter table if exists public.abschriften add column if not exists final_abgesendet boolean default false;
alter table if exists public.mhd_artikel add column if not exists barcode text;
alter table if exists public.mhd_artikel add column if not exists artikelnummer text;
alter table if exists public.mhd_artikel add column if not exists bild_url text;

create table if not exists public.artikel_stammdaten (
  id bigint generated by default as identity primary key,
  barcode text unique not null,
  artikelnummer text,
  name text,
  kategorie text,
  bild_url text,
  updated_at timestamp with time zone default now()
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  mitarbeiter_nummer int,
  endpoint text,
  p256dh text,
  auth text,
  created_at timestamp with time zone default now()
);

alter table public.abschriften disable row level security;
alter table public.mhd_artikel disable row level security;
alter table public.mitarbeiter disable row level security;
alter table public.artikel_stammdaten disable row level security;
alter table public.push_subscriptions disable row level security;
