-- FINAL SQL für Email-Bericht und fehlende Artikel

create table if not exists public.fehlende_artikel (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  barcode text not null,
  hinweis text,
  gemeldet_von text,
  gemeldet_von_nummer int,
  status text default 'offen',
  erledigt_am timestamp with time zone,
  erledigt_von text
);

create index if not exists fehlende_artikel_barcode_status_idx
on public.fehlende_artikel (barcode, status);

alter table if exists public.abschriften add column if not exists typ text default 'ware';
alter table if exists public.abschriften add column if not exists datum date default current_date;
alter table if exists public.abschriften add column if not exists name text;
alter table if exists public.abschriften add column if not exists artikel text;
alter table if exists public.abschriften add column if not exists menge integer default 0;
alter table if exists public.abschriften add column if not exists mitarbeiter text;

alter table public.fehlende_artikel disable row level security;
alter table public.abschriften disable row level security;
alter table public.mhd_artikel disable row level security;
alter table public.mitarbeiter disable row level security;
