
create table if not exists public.mitarbeiter (
  id bigint generated by default as identity primary key,
  nummer int,
  name text not null,
  rolle text not null default 'mitarbeiter',
  passwort text not null default '0000',
  muss_passwort_aendern boolean not null default true
);

delete from public.mitarbeiter a
using public.mitarbeiter b
where a.id > b.id and a.nummer = b.nummer;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'mitarbeiter_nummer_unique') then
    alter table public.mitarbeiter add constraint mitarbeiter_nummer_unique unique (nummer);
  end if;
end $$;

create table if not exists public.mhd_artikel (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  barcode text,
  artikelnummer text,
  artikel text,
  name text,
  kategorie text,
  mhd date,
  menge integer default 1,
  bild_url text,
  mitarbeiter text,
  erstellt_von int
);

create table if not exists public.abschriften (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null
);

alter table public.abschriften add column if not exists artikel_id bigint;
alter table public.abschriften add column if not exists artikel text;
alter table public.abschriften add column if not exists artikelnummer text;
alter table public.abschriften add column if not exists barcode text;
alter table public.abschriften add column if not exists name text;
alter table public.abschriften add column if not exists kategorie text;
alter table public.abschriften add column if not exists mhd date;
alter table public.abschriften add column if not exists menge integer default 0;
alter table public.abschriften add column if not exists bild_url text;
alter table public.abschriften add column if not exists grund text default 'Abschrift';
alter table public.abschriften add column if not exists datum date default current_date;
alter table public.abschriften add column if not exists mitarbeiter text;
alter table public.abschriften add column if not exists mitarbeiter_nummer int;
alter table public.abschriften add column if not exists status text default 'abgeschlossen';

create table if not exists public.online_status (
  nummer int primary key,
  name text not null,
  rolle text not null default 'mitarbeiter',
  last_seen timestamp with time zone default now() not null
);

create table if not exists public.app_settings (
  key text primary key,
  value text,
  updated_at timestamp with time zone default now(),
  updated_by text
);

insert into public.mitarbeiter (nummer, name, rolle, passwort, muss_passwort_aendern)
select v.nummer, v.name, v.rolle, '0000', true
from (values
  (1, 'Lars', 'chef'),
  (2, 'Philipp', 'stationsleitung'),
  (3, 'Denis', 'mitarbeiter'),
  (9, 'Chris', 'mitarbeiter'),
  (17, 'Tizi', 'mitarbeiter'),
  (19, 'Michael', 'chef_temp'),
  (21, 'Mira', 'mitarbeiter'),
  (22, 'Anne', 'mitarbeiter')
) as v(nummer, name, rolle)
where not exists (select 1 from public.mitarbeiter m where m.nummer = v.nummer);

update public.mitarbeiter set name='Lars', rolle='chef' where nummer=1;
update public.mitarbeiter set name='Philipp', rolle='stationsleitung' where nummer=2;
update public.mitarbeiter set name='Denis', rolle='mitarbeiter' where nummer=3;
update public.mitarbeiter set name='Chris', rolle='mitarbeiter' where nummer=9;
update public.mitarbeiter set name='Tizi', rolle='mitarbeiter' where nummer=17;
update public.mitarbeiter set name='Michael', rolle='chef_temp' where nummer=19;
update public.mitarbeiter set name='Mira', rolle='mitarbeiter' where nummer=21;
update public.mitarbeiter set name='Anne', rolle='mitarbeiter' where nummer=22;

alter table public.mitarbeiter disable row level security;
alter table public.mhd_artikel disable row level security;
alter table public.abschriften disable row level security;
alter table public.online_status disable row level security;
alter table public.app_settings disable row level security;
