-- FINALER DATENBANK-FIX FÜR MHD-APP
-- Bitte komplett in Supabase SQL Editor ausführen.

-- Mitarbeiter
create table if not exists public.mitarbeiter (
  id bigint generated by default as identity primary key,
  nummer int unique not null,
  name text not null,
  rolle text not null default 'mitarbeiter',
  passwort text not null default '0000',
  muss_passwort_aendern boolean not null default true
);

alter table public.mitarbeiter add column if not exists nummer int;
alter table public.mitarbeiter add column if not exists name text;
alter table public.mitarbeiter add column if not exists rolle text default 'mitarbeiter';
alter table public.mitarbeiter add column if not exists passwort text default '0000';
alter table public.mitarbeiter add column if not exists muss_passwort_aendern boolean default true;

-- MHD Artikel
create table if not exists public.mhd_artikel (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null
);

alter table public.mhd_artikel add column if not exists barcode text;
alter table public.mhd_artikel add column if not exists artikelnummer text;
alter table public.mhd_artikel add column if not exists artikel text;
alter table public.mhd_artikel add column if not exists name text;
alter table public.mhd_artikel add column if not exists kategorie text;
alter table public.mhd_artikel add column if not exists mhd date;
alter table public.mhd_artikel add column if not exists menge integer default 1;
alter table public.mhd_artikel add column if not exists bild_url text;
alter table public.mhd_artikel add column if not exists mitarbeiter text;
alter table public.mhd_artikel add column if not exists erstellt_von int;

update public.mhd_artikel set artikel = coalesce(artikel, name, 'Artikel') where artikel is null;
update public.mhd_artikel set name = coalesce(name, artikel, 'Artikel') where name is null;

-- Abschriften
create table if not exists public.abschriften (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null
);

alter table public.abschriften add column if not exists artikel text default 'Artikel';
alter table public.abschriften add column if not exists artikel_id bigint;
alter table public.abschriften add column if not exists artikelnummer text;
alter table public.abschriften add column if not exists barcode text;
alter table public.abschriften add column if not exists name text;
alter table public.abschriften add column if not exists kategorie text;
alter table public.abschriften add column if not exists mhd date;
alter table public.abschriften add column if not exists menge integer default 0;
alter table public.abschriften add column if not exists bild_url text;
alter table public.abschriften add column if not exists grund text default 'Abschrift';
alter table public.abschriften add column if not exists datum date default current_date;
alter table public.abschriften add column if not exists mitarbeiter text;
alter table public.abschriften add column if not exists mitarbeiter_nummer int;

update public.abschriften set artikel = coalesce(artikel, name, 'Artikel') where artikel is null;
update public.abschriften set name = coalesce(name, artikel, 'Artikel') where name is null;

-- Mitarbeiter einfügen/aktualisieren
insert into public.mitarbeiter (nummer, name, rolle, passwort, muss_passwort_aendern) values
(1, 'Lars', 'chef', '0000', true),
(2, 'Philipp', 'stationsleitung', '0000', true),
(3, 'Denis', 'mitarbeiter', '0000', true),
(9, 'Chris', 'mitarbeiter', '0000', true),
(17, 'Tizi', 'mitarbeiter', '0000', true),
(19, 'Michael', 'chef_temp', '0000', true),
(21, 'Mira', 'mitarbeiter', '0000', true),
(22, 'Anne', 'mitarbeiter', '0000', true)
on conflict (nummer) do update set name = excluded.name, rolle = excluded.rolle;

-- Für diese einfache App RLS deaktivieren
alter table public.mitarbeiter disable row level security;
alter table public.mhd_artikel disable row level security;
alter table public.abschriften disable row level security;



-- Abschriften Freigabe / Tagesabschluss
alter table public.abschriften add column if not exists finalisiert boolean default false;
alter table public.abschriften add column if not exists finalisiert_am timestamp with time zone;
alter table public.abschriften add column if not exists finalisiert_von text;
update public.abschriften set finalisiert = false where finalisiert is null;
