create table if not exists public.mitarbeiter (
  id bigint generated by default as identity primary key,
  nummer int unique not null,
  name text not null,
  rolle text not null default 'mitarbeiter',
  passwort text not null default '0000',
  muss_passwort_aendern boolean not null default true
);

create table if not exists public.mhd_artikel (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  barcode text,
  artikelnummer text,
  name text not null,
  kategorie text not null,
  mhd date not null,
  menge integer not null default 1,
  bild_url text,
  mitarbeiter text,
  erstellt_von int
);

create table if not exists public.abschriften (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  artikel_id bigint,
  artikelnummer text,
  barcode text,
  name text not null,
  kategorie text,
  mhd date,
  menge integer not null default 1,
  bild_url text,
  grund text not null,
  datum date default current_date,
  mitarbeiter text,
  mitarbeiter_nummer int
);

insert into public.mitarbeiter (nummer, name, rolle, passwort, muss_passwort_aendern) values
(1, 'Lars', 'chef', '0000', true),
(2, 'Philipp', 'stationsleitung', '0000', true),
(3, 'Denis', 'mitarbeiter', '0000', true),
(9, 'Chris', 'mitarbeiter', '0000', true),
(17, 'Tizi', 'mitarbeiter', '0000', true),
(19, 'Michael', 'chef_temp', '0000', true),
(21, 'Mira', 'mitarbeiter', '0000', true),
(22, 'Anne', 'mitarbeiter', '0000', true)
on conflict (nummer) do update set name = excluded.name, rolle = excluded.rolle;

alter table public.mitarbeiter disable row level security;
alter table public.mhd_artikel disable row level security;
alter table public.abschriften disable row level security;
