-- Komplett-Fix für bestehende Supabase Tabellen

create table if not exists public.mitarbeiter (
  id bigint generated by default as identity primary key,
  nummer int unique not null,
  name text not null,
  rolle text not null default 'mitarbeiter',
  passwort text not null default '0000',
  muss_passwort_aendern boolean not null default true
);

create table if not exists public.mhd_artikel (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  barcode text,
  artikelnummer text,
  artikel text,
  name text not null,
  kategorie text not null,
  mhd date not null,
  menge integer not null default 1,
  bild_url text,
  mitarbeiter text,
  erstellt_von int
);

create table if not exists public.abschriften (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  artikel text default 'Artikel' not null
);

alter table public.abschriften add column if not exists artikel_id bigint;
alter table public.abschriften add column if not exists artikelnummer text;
alter table public.abschriften add column if not exists barcode text;
alter table public.abschriften add column if not exists name text;
alter table public.abschriften add column if not exists kategorie text;
alter table public.abschriften add column if not exists mhd date;
alter table public.abschriften add column if not exists menge integer default 0;
alter table public.abschriften add column if not exists bild_url text;
alter table public.abschriften add column if not exists grund text default 'Abschrift';
alter table public.abschriften add column if not exists datum date default current_date;
alter table public.abschriften add column if not exists mitarbeiter text;
alter table public.abschriften add column if not exists mitarbeiter_nummer int;

update public.abschriften set artikel = coalesce(artikel, name, 'Artikel') where artikel is null;
update public.abschriften set name = coalesce(name, artikel, 'Artikel') where name is null;

insert into public.mitarbeiter (nummer, name, rolle, passwort, muss_passwort_aendern) values
(1, 'Lars', 'chef', '0000', true),
(2, 'Philipp', 'stationsleitung', '0000', true),
(3, 'Denis', 'mitarbeiter', '0000', true),
(9, 'Chris', 'mitarbeiter', '0000', true),
(17, 'Tizi', 'mitarbeiter', '0000', true),
(19, 'Michael', 'chef_temp', '0000', true),
(21, 'Mira', 'mitarbeiter', '0000', true),
(22, 'Anne', 'mitarbeiter', '0000', true)
on conflict (nummer) do update set name = excluded.name, rolle = excluded.rolle;

alter table public.mitarbeiter disable row level security;
alter table public.mhd_artikel disable row level security;
alter table public.abschriften disable row level security;



-- Online Status für Chef/Stationsleitung
create table if not exists public.online_status (
  nummer int primary key,
  name text not null,
  rolle text not null default 'mitarbeiter',
  last_seen timestamp with time zone default now() not null
);

alter table public.online_status disable row level security;



-- App Einstellungen für Dienstpläne und weitere Inhalte
create table if not exists public.app_settings (
  key text primary key,
  value text,
  updated_at timestamp with time zone default now(),
  updated_by text
);

alter table public.app_settings disable row level security;
